version: 2.1

executors:
  cpp-executor:
    docker:
      - image: ubuntu:latest
    resource_class: small
    environment:
      CXX: g++
      CC: gcc

jobs:
  build-and-test:
    executor: cpp-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y cmake g++ git make
            apt-get install -y libgtest-dev
            cd /usr/src/googletest
            cmake . && make
            cp lib/*.a /usr/lib
      - run:
          name: Build Project
          command: |
            mkdir -p build
            cd build
            cmake ..
            make
      - run:
          name: Run Unit Tests
          command: |
            cd build
            ctest --output-on-failure
      - store_test_results:
          path: build/test-results  # Store test results for CircleCI UI

workflows:
  version: 2
  test-and-coverage:
    jobs:
      - build-and-test

